"""Distinct, practical AI workflow guides. Keep one search intent per URL.

Each entry has a task-specific input, procedure, reusable prompt, review gate,
and measurement. This deliberately avoids duplicating the broad strategy pillar.
"""

from html import escape

# A small, task-specific exercise makes each guide testable before a team adopts it.
# These are illustrative exercises, not claims about work performed for clients.
TRIALS = {
    "chatgpt-weekly-operations-meeting-agenda": "Try it with one overdue action, a declining KPI, and a routine update. The agenda should put the KPI decision first, assign the overdue action to a named role, and move the routine update out of meeting time.",
    "chatgpt-client-proposal-first-draft": "Give it discovery notes that mention a possible extra service but an approved scope that omits it. The proposal must keep the extra service out of deliverables and mark any missing price or deadline for confirmation.",
    "chatgpt-sales-call-follow-up-email": "Use notes with a promised document and a tentative next meeting. The email should state the document commitment while treating the meeting date as tentative until it is confirmed.",
    "chatgpt-customer-complaint-triage": "Include a complaint requesting a refund when the supplied policy does not authorize one. A usable draft acknowledges the problem and routes the remedy request without promising payment.",
    "chatgpt-draft-sop-from-screen-recording-notes": "Test a process with one missing screen step and one exception path. The SOP should flag the missing click and tell the operator what to do when the normal path fails.",
    "chatgpt-local-service-faq-drafts": "Provide real questions about travel radius and weekend appointments, but no approved answer for either. The draft should leave both answers pending rather than inventing a radius or availability.",
    "chatgpt-invoice-dispute-summary": "Use an invoice, a signed scope, and a change request with no approval record. The timeline should show the disputed charge separately and identify approval as missing evidence.",
    "chatgpt-structured-interview-questions-small-business": "Give the same role scorecard to two interviewers. Both should receive identical core questions and a rubric that scores observable job evidence rather than personal impressions.",
    "chatgpt-cash-flow-meeting-prep": "Include a receivable that has moved beyond its expected collection date. The brief should trace the change to the forecast row and ask for an owner and revised assumption.",
    "chatgpt-customer-onboarding-checklist": "Use a signed scope with a kickoff dependent on customer access. The checklist should place access before kickoff and show who verifies that the account works.",
    "chatgpt-vendor-comparison-table": "Compare two proposals where one omits a renewal term. The table should leave that field unknown, cite the other proposal's term, and avoid awarding a score for the missing fact.",
    "chatgpt-post-project-retrospective": "Include a delayed milestone and conflicting explanations in team notes. The retrospective should distinguish the dated milestone record from hypotheses and assign a follow-up to test the cause.",
    "claude-extract-contract-obligations": "Include an original agreement and an amendment that changes a deadline. The register should cite both sections and flag which deadline controls for legal review.",
    "claude-compare-policy-versions": "Compare drafts with one renumbered section and one changed approval rule. The output should exclude renumbering from substantive changes and identify who follows the new rule.",
    "claude-board-packet-questions": "Use a packet with a budget variance but no explanation. A useful question should point to the variance table and ask management for the cause before the board votes.",
    "claude-rfp-requirements-matrix": "Add a mandatory requirement that appears only in an attachment. The matrix should capture it with the attachment reference and keep response ownership visible.",
    "claude-commercial-lease-clause-summary": "Use a lease with separate base rent, operating expense, and renewal clauses. The summary should keep those obligations distinct and cite the clause for every date or payment trigger.",
    "claude-synthesize-customer-interviews": "Provide interviews where one customer contradicts the majority. The synthesis should count the pattern, preserve the dissenting evidence, and avoid treating a small sample as market proof.",
    "claude-due-diligence-document-register": "Add two similarly named files from different periods. The register should identify each period, flag the older version, and show which request remains unanswered.",
    "claude-incident-timeline-from-notes": "Provide notes with a reported event time and a later log timestamp. The timeline should label which time is observed and which is reported instead of silently choosing one.",
    "claude-grant-application-evidence-map": "Use a grant question requesting a measured outcome but supply only a narrative claim. The evidence map should identify the missing measurement and the owner who can provide it.",
    "claude-compare-supplier-agreements": "Compare agreements with different termination notice periods. The table should cite both clauses and show the operational consequence of missing either deadline.",
    "claude-employee-handbook-qa-draft": "Ask a question that the handbook does not answer. The draft should say the policy is not established in the supplied text and refer the employee to the policy owner.",
    "claude-quarterly-strategy-memo-draft": "Include an initiative that missed its target and a proposal to expand it. The memo should separate actual results from the expansion case and name the evidence needed for a decision.",
    "gpt-sales-discovery-note-formatter": "Feed the GPT notes with an explicit customer need and an unstated budget. It should preserve the need, mark budget unknown, and avoid filling the gap with an assumed number.",
    "gpt-brand-voice-reviewer-business": "Test one approved sample and one off-brand draft. The GPT should point to a specific voice rule for each proposed edit and leave factual claims for a separate source check.",
    "gpt-service-estimate-intake-checker": "Submit an intake with a service address but no access instructions. The checker should return the missing field and stop before producing a ready-to-send estimate.",
    "gpt-internal-sop-lookup": "Ask about a procedure that changed in the latest SOP. The GPT should cite the current version and avoid presenting an older file as the rule.",
    "gpt-meeting-decision-log": "Provide notes containing a suggestion, a decision, and an unassigned action. The log should keep all three categories separate and flag the action owner as missing.",
    "gpt-support-reply-drafter": "Test a ticket where the customer asks for a policy exception. The draft should acknowledge the request and route the exception to an authorized reviewer without promising it.",
    "gpt-proposal-scope-checker": "Give the GPT a proposal that adds a deliverable absent from the signed scope. Its output should identify the exact mismatch and withhold a pass until the scope is corrected.",
    "gpt-content-brief-generator": "Supply one search intent and a list of existing pages. The brief should select one target URL, identify the reader's task, and flag a proposed angle that duplicates an existing page.",
    "gpt-new-hire-onboarding-qa": "Ask about a benefit that differs by location when the supplied policy covers only one location. The GPT should state that limit and refer the new hire to the appropriate owner.",
    "gpt-invoice-coding-suggestions": "Include an invoice line that could fit two expense codes. The GPT should show both candidates and the missing evidence; a finance reviewer makes the final coding choice.",
    "gpt-guest-message-draft-short-term-rental": "Use a reservation with a confirmed check-in time but no approved early arrival. The message should share the confirmed time and avoid offering early access.",
    "test-custom-gpt-before-team-rollout": "Run a normal request, a missing-data request, and a request outside the GPT's scope. Approval requires a correct result, a visible uncertainty, and a safe refusal or handoff respectively.",
    "ai-sales-lead-qualification-workflow": "Test a lead with the right industry but no buying timeline. The workflow should keep the lead in a review state and avoid treating missing timing as purchase intent.",
    "ai-sales-to-delivery-handoff": "Include a deal with an agreed deliverable and an unresolved implementation assumption. The handoff should surface the assumption before delivery accepts a date.",
    "ai-support-ticket-routing-small-business": "Use a ticket containing a routine billing question and a possible safety concern. The safety escalation should take precedence over the routine category.",
    "ai-accounts-receivable-follow-up-drafts": "Include a past-due invoice with an open service dispute. The draft should acknowledge the dispute and route it for review rather than sending a generic payment demand.",
    "ai-weekly-kpi-commentary": "Provide a KPI change caused by a revised definition rather than performance. The commentary should explain the definition break before interpreting the trend.",
    "ai-inventory-exception-review": "Feed in one apparent stockout caused by a late data sync. The exception brief should flag the timestamp and request verification before recommending a reorder.",
    "ai-field-service-dispatch-brief": "Use a job with a known fault but no access window. The brief should keep the fault details and mark the access window as a dispatch blocker.",
    "ai-restaurant-review-response-drafts": "Test a public review alleging a specific service failure. The response should avoid revealing account details and route fact checking to the manager before publication.",
    "ai-agency-creative-brief-handoff": "Provide a signed campaign goal but two conflicting audience descriptions. The brief should state the conflict and request an owner decision before creative work starts.",
    "ai-property-maintenance-intake": "Use a request mentioning water near an electrical outlet but no photos. The intake should escalate the potential hazard immediately rather than wait for a complete routine ticket.",
    "ai-nonprofit-donor-thank-you-drafts": "Include a restricted donation and a general impact story. The note should honor the restriction and avoid claiming that this particular gift funded the story.",
    "ai-executive-decision-brief": "Compare a lower-cost option with an unverified delivery risk. The brief should show the cost evidence, label the risk assumption, and say what information would change the decision.",
    "choose-first-ai-pilot-small-business": "Compare a high-volume task with poor source data against a smaller task with clean examples and an available reviewer. The pilot choice should account for review capacity, not volume alone.",
    "measure-ai-workflow-roi-human-review": "Time a baseline task and an AI-assisted task including prompt preparation, review, corrections, and rework. The calculation should use accepted outputs rather than drafts produced.",
    "small-business-ai-data-policy-checklist": "Walk through a customer record, a public document, and an internal financial report. Staff should be able to identify which approved tool and permission applies to each.",
    "redact-customer-data-before-ai-analysis": "Provide a sample record with names, account numbers, and facts needed for analysis. The redacted version should remove identifiers while retaining only the fields needed for the stated question.",
    "ai-output-review-checklist-business": "Test the checklist on a draft with a wrong date, an unsupported promise, and a missing citation. Reviewers should catch all three before approving use.",
    "compare-chatgpt-claude-business-task": "Give both tools the same approved document set and output rubric. Compare accuracy, traceability, review effort, and cost on accepted results, not writing style alone.",
    "human-approval-gates-ai-automation": "Map a workflow that drafts, approves, and sends a customer message. The gate should sit before sending and name who can stop or reverse the action.",
    "audit-ai-prompt-library-stale-rules": "Add a prompt containing an outdated price and another with an expired policy link. The audit should identify both, record their owners, and prevent reuse until updated.",
    "build-ai-pilot-evaluation-set": "Build examples with complete, missing, and contradictory source data. The test set should score whether the workflow flags uncertainty as well as whether it gets routine cases right.",
    "build-versus-buy-ai-workflow-small-business": "Compare a vendor product with a custom workflow using the same acceptance test. Include maintenance, data access, exit, and reviewer cost in both options.",
    "train-staff-report-ai-errors": "Give staff a polished answer with one fabricated source reference. The exercise should ask them to stop use, preserve the evidence, and report the failure to the workflow owner.",
    "review-ai-vendor-data-terms-pilot": "Take a pilot involving customer records and a vendor document silent on retention. The review should mark retention unanswered and hold the upload until an authorized owner resolves it.",
}

CLUSTERS = [
    {
        "slug": "chatgpt-business-workflows",
        "title": "ChatGPT Workflows for Small Business",
        "description": "Task-by-task ChatGPT guides for owners and managers: meetings, proposals, sales handoffs, and service operations.",
        "intro": "Start with work that already has an owner, a source document, and a clear definition of done. These ChatGPT workflows turn a messy input into a draft artifact for a person to inspect. Keep customer and employee information within the controls approved by your organization.",
        "decision": "Choose a guide by the document you need to produce. For a reusable team instruction set, continue to the GPT systems hub; for a long document review, use the Claude hub. Do not use the general AI strategy pillar as a substitute for the actual task instructions below.",
        "guides": [
            ("ChatGPT for Weekly Operations Meetings", "chatgpt-weekly-operations-meeting-agenda", "how to use ChatGPT for weekly operations meeting agendas", "Last week's actions, current KPI snapshot, unresolved blockers, and the attendee list.", "Ask for a 30-minute agenda ordered by decisions required, with owner and time box for each item. Reserve the final five minutes for new commitments and carryovers.", "Using only the notes below, draft a 30-minute operations agenda. Separate decisions, updates, and blockers. For each decision list owner, evidence needed, and minutes allotted. Flag missing facts instead of inventing them.", "The meeting owner checks every KPI against its source and removes items that can be handled asynchronously. Assign actual people only after they accept the work.", "Minutes spent on status updates and the share of action items closed before the next meeting."),
            ("ChatGPT for Client Proposal First Drafts", "chatgpt-client-proposal-first-draft", "how to use ChatGPT to draft a small business client proposal", "Discovery notes, approved scope, exclusions, delivery dates, and current pricing sheet.", "Have ChatGPT produce a one-page outline before full prose. Structure it as client problem, proposed work, deliverables, timeline, assumptions, and next step.", "Draft a client proposal from these approved notes. Do not add services, outcomes, deadlines, or prices absent from the source. Mark any missing commercial term [CONFIRM]. Use plain language and a scope table.", "The account owner reconciles every promise against the statement of work and confirms pricing with the authorized approver before sending.", "Revision rounds and the percentage of proposals accepted without scope clarification."),
            ("ChatGPT for Sales Call Follow-Up", "chatgpt-sales-call-follow-up-email", "how to use ChatGPT for sales call follow-up emails", "Consent-based call notes, prospect's stated priorities, commitments, and the agreed next meeting.", "Extract commitments first, then draft a short follow-up with the prospect's language and one specific next action. Keep uncertain details in a separate questions list.", "From this call summary, write a follow-up email under 170 words. Recap the customer's stated problem, what we agreed to send, and the dated next step. Do not claim interest or budget we did not hear.", "A salesperson checks names, dates, attachments, and whether the recap reflects what the prospect actually said. Send through the normal CRM workflow.", "Reply rate and whether next meetings happen on the agreed date."),
            ("ChatGPT for Customer Complaint Triage", "chatgpt-customer-complaint-triage", "how to use ChatGPT to triage customer complaints", "The customer's message, order or service record, service policy, and escalation rules.", "Classify the issue by urgency and desired remedy, summarize the facts, and draft an empathetic acknowledgement. Route refund, safety, or legal requests to the designated owner.", "Summarize this complaint in five facts, identify what the customer is asking for, and draft an acknowledgement without promising a remedy. Cite the policy section used and label any uncertainty.", "A support lead verifies identity, policy, and any proposed remedy. Sensitive complaints remain under human control, including the final response.", "Time to first accurate response and reopened tickets caused by misclassification."),
            ("ChatGPT for Standard Operating Procedures", "chatgpt-draft-sop-from-screen-recording-notes", "how to use ChatGPT to write an SOP from process notes", "A screen-recording transcript or observed steps, system permissions, exception cases, and process owner.", "Turn the observed sequence into prerequisites, numbered actions, decision points, and a final verification. Ask the operator to test it without help.", "Convert these process notes into an SOP for a new hire. Preserve the exact order, mark ambiguous clicks [VERIFY], list required access, and include what to do when the normal path fails.", "The process owner performs the procedure from the draft in a safe environment and corrects every mislabeled screen or missing exception.", "First-run completion rate by a new teammate and the count of clarification questions."),
            ("ChatGPT for Local Service FAQ Drafts", "chatgpt-local-service-faq-drafts", "how to use ChatGPT to draft a local service business FAQ", "Actual customer questions, current service area, hours, booking rules, and approved policies.", "Group repeated questions by booking, service, pricing, and preparation. Write concise answers grounded only in current policy, then publish where customers already look.", "Draft answers to these real customer questions in 60 words each. Use only the supplied business facts. If the price, radius, or policy is missing, write [OWNER TO CONFIRM]. Do not invent guarantees.", "The service manager verifies hours, geography, fees, and policy language. Recheck whenever operations change.", "Reduction in repeated pre-sale questions and FAQ-assisted bookings."),
            ("ChatGPT for Invoice Dispute Summaries", "chatgpt-invoice-dispute-summary", "how to use ChatGPT to summarize an invoice dispute", "Invoice, signed scope, change orders, payment history, and the customer's dispute message.", "Build a dated fact table, separate agreed scope from contested charges, and identify what evidence is still missing. Keep analysis separate from the reply draft.", "Create a neutral timeline of this invoice dispute with a source reference for each claim. List uncontested and contested amounts separately. Draft a factual response with no threat or legal conclusion.", "The account or finance owner checks amounts against records and routes contractual questions to appropriate counsel before any final position.", "Time to assemble the case file and disputed invoices resolved without a second evidence request."),
            ("ChatGPT for Hiring Interview Questions", "chatgpt-structured-interview-questions-small-business", "how to use ChatGPT to create structured interview questions", "Job outcomes, essential skills, scorecard, and the same interview time for each candidate.", "Generate behavior-based questions mapped to competencies, plus a scoring rubric with observable signals. Ask every candidate the same core questions.", "Create six structured interview questions for this role and a 1–4 rubric for each. Focus on job-related evidence; exclude protected traits, family status, and assumptions about background.", "The hiring manager checks relevance, local employment requirements, and consistent use of the rubric. A person makes the hiring decision.", "Interviewer agreement on scores and the percentage of questions tied to a defined role outcome."),
            ("ChatGPT for Cash Flow Meeting Preparation", "chatgpt-cash-flow-meeting-prep", "how to use ChatGPT to prepare a cash flow meeting", "An approved cash flow forecast, receivables aging, upcoming obligations, and known assumptions.", "Summarize changes from the prior forecast, ask for the source of unusually large movements, and frame decisions about timing and collections.", "Using these approved figures, draft a cash flow meeting brief: three changes, their source rows, decisions needed, and unanswered questions. Do not calculate from missing data or present a forecast as certainty.", "Finance reconciles totals and assumptions before distribution. Confirm action owners for each collection or spending decision.", "Time from data close to meeting brief and number of material errors found in review."),
            ("ChatGPT for New Customer Onboarding Checklists", "chatgpt-customer-onboarding-checklist", "how to use ChatGPT to make a customer onboarding checklist", "Signed scope, customer intake form, assigned team, milestones, and required approvals.", "Map the first 30 days into customer and internal tasks, with dependencies and a clear handoff from sales to delivery.", "Build a customer onboarding checklist from this signed scope. Show owner, due trigger, required input, and completion evidence for each step. Put unknowns in a separate section.", "The delivery lead confirms capacity, timelines, and who owns each handoff. Share only the customer-facing portion externally.", "Days to first value and onboarding tasks completed on schedule."),
            ("ChatGPT for Vendor Comparison Tables", "chatgpt-vendor-comparison-table", "how to use ChatGPT to compare small business vendors", "Current proposals, must-have requirements, evaluation weights, and contract terms.", "Normalize each vendor against identical criteria. Quote the evidence location for each score and leave blanks where a proposal is silent.", "Build a comparison table for these vendors using only the attached proposals. Score our stated requirements with source citations, list exclusions and renewal terms, and mark missing evidence as unknown.", "A buyer checks each score against original quotes and negotiates or requests missing terms. Do not treat polished prose as verified vendor performance.", "Time to shortlist and the number of decision criteria supported by documented evidence."),
            ("ChatGPT for Post-Project Retrospectives", "chatgpt-post-project-retrospective", "how to use ChatGPT to run a small business retrospective", "Project plan, actual milestones, issue log, customer feedback, and team observations.", "Sort events into what happened, why, and what to change. Produce a short action register with a single owner and review date per change.", "From these records, prepare a blameless retrospective. Separate documented facts from interpretations, include two things to repeat and two process changes, and give each change a measurable follow-up.", "The facilitator asks participants to correct the record and agree on causes before assigning process changes.", "Actions implemented by the next project and recurrence of the same delay or defect."),
        ],
    },
    {
        "slug": "claude-business-documents",
        "title": "Claude for Business Documents and Analysis",
        "description": "Claude workflows for reviewing lengthy business documents, extracting decisions, and producing drafts a human can verify.",
        "intro": "Document-heavy tasks benefit from a stable source set and a clear citation discipline. Claude can help create a first pass through long material, but the owner of a contract, policy, or financial decision must check the original documents. Redact or use approved workspace controls before sharing sensitive files.",
        "decision": "Begin with the document and the question you need answered. Use the comparison guide for competing versions, the extraction guide for a structured register, and the drafting guide when you need a new artifact. The parent AI pillar covers prioritization rather than document-level execution.",
        "guides": [
            ("Claude for Contract Obligation Extraction", "claude-extract-contract-obligations", "how to use Claude to extract obligations from a contract", "Executed agreement, exhibits, amendments, and a list of parties.", "Request a table of obligation, responsible party, trigger, deadline, and exact clause reference. Ask Claude to identify conflicting amendments instead of resolving them silently.", "Extract each operational obligation from these documents. Quote only the clause number and a short paraphrase, distinguish mandatory from optional language, and label uncertain interpretations for counsel.", "Legal or contract operations verifies clause references and precedence of amendments. Calendar dates only after the trigger and responsible party are confirmed.", "Missed contractual milestones and extraction errors caught in review."),
            ("Claude for Comparing Two Policy Versions", "claude-compare-policy-versions", "how to compare policy versions with Claude", "Old policy, proposed policy, effective dates, and affected roles.", "Compare sections by meaning, not just wording. Produce added, removed, and changed requirements with section references and an employee impact note.", "Compare version A and B. List only substantive changes, cite both section numbers, and describe who must act differently. Mark renumbering with no policy change separately.", "The policy owner checks every difference and approves the effective date and communication plan.", "Material changes missed at launch and clarification requests after rollout."),
            ("Claude for Board Packet Question Lists", "claude-board-packet-questions", "how to use Claude to prepare board packet questions", "Board agenda, financial packet, prior minutes, and open actions.", "Ask for questions organized by decision, risk, and missing evidence. Tie each question to a page or table and distinguish management's assertion from source data.", "Read this packet and prepare ten board-level questions. Cite page or section for each. Prioritize decisions on the agenda and flag figures that cannot be reconciled from the packet alone.", "The chair or executive reviews sensitivity and removes questions already answered in supplementary material.", "Decisions postponed for missing information and time spent locating supporting pages."),
            ("Claude for RFP Requirement Matrices", "claude-rfp-requirements-matrix", "how to use Claude to build an RFP requirements matrix", "Complete request for proposal, attachments, deadlines, and response instructions.", "Extract every requirement into mandatory, scored, administrative, and ambiguous buckets with page citations and response owner.", "Create an RFP compliance matrix with requirement, exact source location, response evidence needed, internal owner, and due date. Do not assume an unanswered item is optional.", "The bid lead checks appendices and addenda, then assigns owners and confirms submission rules directly from the source.", "Missed mandatory requirements and time spent assembling the first compliance checklist."),
            ("Claude for Lease Clause Summaries", "claude-commercial-lease-clause-summary", "how to use Claude to summarize a commercial lease", "Lease, exhibits, amendments, renewal notices, and commencement records.", "Summarize rent changes, options, notice periods, maintenance, and assignment provisions in a clause-indexed table.", "Summarize operational lease terms with section references. Separate fixed dates from dates triggered by an event. Do not infer legal effect where language is disputed; flag that for counsel.", "The property or legal owner verifies dates and negotiable rights from the signed documents before relying on the summary.", "Notice dates captured correctly and time to answer a lease operations question."),
            ("Claude for Customer Research Synthesis", "claude-synthesize-customer-interviews", "how to synthesize customer interviews with Claude", "Consented interview notes, participant identifiers, research questions, and sampling context.", "Code observations by theme, count supporting participants, preserve contradictory evidence, and separate direct evidence from hypotheses.", "Synthesize these interviews into needs, pain points, and exceptions. Give an anonymized source ID for each theme, count distinct participants, and avoid treating a single quote as a universal pattern.", "The researcher checks the source passages and demographic balance before prioritizing product changes.", "Themes confirmed in follow-up research and decisions linked to source evidence."),
            ("Claude for Due Diligence Document Registers", "claude-due-diligence-document-register", "how to use Claude to organize business acquisition diligence documents", "Data room index, request list, received files, and version dates.", "Produce a register of requested versus received evidence, stale documents, and unanswered questions. Keep an audit trail of source filenames.", "Compare the diligence request list with this data room index. Mark received, partial, missing, or outdated; cite filenames and dates; propose one follow-up question per gap.", "The deal team confirms document completeness and routes accounting, legal, and tax conclusions to the respective specialists.", "Open requests at each diligence checkpoint and duplicate asks sent to the seller."),
            ("Claude for Incident Timeline Reconstruction", "claude-incident-timeline-from-notes", "how to use Claude to build an incident timeline", "Timestamped tickets, internal updates, system logs, and customer reports.", "Merge events into one chronology with source references and time zone. Separate observed events from explanations and unresolved gaps.", "Build an incident timeline from these records. Preserve original timestamps and time zones, cite the source for each event, and label any inferred sequence as unverified.", "The incident lead reconciles clock differences and approves the timeline before using it in a customer or leadership report.", "Time to produce a verified timeline and corrections after review."),
            ("Claude for Grant Application Evidence Maps", "claude-grant-application-evidence-map", "how to use Claude to map grant application evidence", "Application instructions, eligibility criteria, program records, and supporting documents.", "Match each criterion to available evidence and identify missing proof before drafting narrative answers.", "Make an evidence map for this grant application: requirement, source file and page, owner, and gap. Do not invent outcomes or imply eligibility where the record is unclear.", "The program owner verifies every metric and eligibility claim, then checks submission rules and deadlines.", "Requirements supported by documented evidence before submission."),
            ("Claude for Supplier Agreement Comparison", "claude-compare-supplier-agreements", "how to use Claude to compare supplier agreements", "Current and proposed supplier agreements, pricing schedules, and service levels.", "Compare commercial terms, termination, liability, data use, and service credits in aligned rows with source sections.", "Compare these supplier agreements by clause topic. Show both positions and section citations, identify material operational differences, and leave legal recommendations to counsel.", "Procurement validates prices and volume assumptions; counsel evaluates risk and negotiates final language.", "Unexpected obligations found after signing and time to prepare negotiation issues."),
            ("Claude for Employee Handbook Q&A Drafts", "claude-employee-handbook-qa-draft", "how to use Claude to draft employee handbook answers", "Current approved handbook, effective date, jurisdiction, and employee's question.", "Find the relevant policy sections and draft a plain-language answer with a reference and escalation path where the policy is silent.", "Answer this handbook question using only the approved policy. Cite its section, distinguish policy from interpretation, and say when HR must review a specific case.", "HR checks current version and local requirements before an answer is sent. Avoid uploading personnel facts outside approved systems.", "Questions resolved with the current policy and corrections issued by HR."),
            ("Claude for Quarterly Strategy Memo Drafts", "claude-quarterly-strategy-memo-draft", "how to use Claude to draft a quarterly strategy memo", "Quarterly KPIs, prior priorities, customer signals, and leadership decisions.", "Create a concise memo with results versus plan, evidence for each proposed priority, trade-offs, and explicit decisions needed.", "Draft a strategy memo from these approved sources. For every recommendation include the supporting metric or observation, an alternative, and what leadership must decide. Mark missing baselines.", "The executive owner verifies numbers and owns the judgments; circulate only the approved draft to the intended audience.", "Decisions made at the review meeting and action owners assigned afterward."),
        ],
    },
    {
        "slug": "custom-gpts-business",
        "title": "Custom GPTs for Repeatable Business Tasks",
        "description": "How to scope, test, and maintain reusable GPT instructions for distinct small business jobs.",
        "intro": "A reusable GPT is useful when a team repeats the same bounded task with the same rules. Write the job description, examples, limits, and escalation path before building it. Keep access to source files and external actions aligned with your workspace policy.",
        "decision": "The guides below are organized by the artifact the GPT produces. Begin with a draft-only role and a test set of known examples. Move to connected actions only after the owner has a way to review errors, permissions, and changes.",
        "guides": [
            ("Build a GPT for Sales Discovery Notes", "gpt-sales-discovery-note-formatter", "how to build a GPT for sales discovery notes", "A consented call transcript, CRM field definitions, qualification criteria, and examples of good notes.", "Define a fixed field order: problem, current process, decision process, timing, agreed next step. Teach the GPT to distinguish customer statements from seller assumptions.", "Format these discovery notes for our CRM fields. Use only what the prospect said, attach a source excerpt to key claims, and mark missing qualification fields unknown.", "The salesperson checks the transcript and edits the CRM record before saving; do not infer budget or authority.", "Time to complete the record and missing or incorrect qualification fields."),
            ("Build a GPT for Brand Voice Checks", "gpt-brand-voice-reviewer-business", "how to build a GPT to review brand voice", "Approved style guide, prohibited claims, target audience, and before-and-after examples.", "Make the GPT a reviewer that highlights departures from the guide, explains the rule, and suggests a revision. Preserve factual claims unless a source contradicts them.", "Review this draft against the attached style guide. Return rule, offending passage, and suggested edit. Do not add a testimonial, guarantee, or performance claim.", "The editor accepts or rejects each change and checks that tone edits did not alter meaning or introduce unsupported promises.", "Editorial revisions per asset and off-brand copy found after approval."),
            ("Build a GPT for Service Estimate Intake", "gpt-service-estimate-intake-checker", "how to build a GPT for service estimate intake", "Service catalog, required measurements, location rules, and examples of complete requests.", "Have the GPT request missing information and output a structured intake record. Keep pricing and final estimates with the authorized estimator.", "Check this service request for required intake fields. Ask only for missing facts and format the completed record for our estimator. Do not quote a price or promise availability.", "An estimator verifies measurements, access constraints, and service fit before producing any quote.", "Requests requiring a second intake conversation and estimate turnaround time."),
            ("Build a GPT for SOP Lookup", "gpt-internal-sop-lookup", "how to build a GPT for internal SOP lookup", "Current approved SOP library, version dates, owners, and permission boundaries.", "Instruct the GPT to answer from retrieved procedures with document and section references, and to abstain when no current instruction exists.", "Answer the employee's process question only from approved SOPs. Cite the document and section, state its effective date, and say when to ask the process owner.", "The process owner checks a sample of answers after every SOP revision; revoke outdated documents promptly.", "Questions answered with a valid citation and incidents caused by stale guidance."),
            ("Build a GPT for Meeting Decision Logs", "gpt-meeting-decision-log", "how to build a GPT for meeting decision logs", "Approved meeting notes, attendee list, decision authority, and action register format.", "Extract decisions separately from proposals and open questions. Give each confirmed action an owner, trigger, and due date only when stated.", "From these notes, produce decisions, actions, and unresolved questions in separate tables. Quote the supporting line for each decision and leave unstated owners blank.", "The meeting chair confirms authority and circulates the log for correction before it becomes the record.", "Unassigned actions and decisions later disputed because they were only proposals."),
            ("Build a GPT for Support Reply Drafts", "gpt-support-reply-drafter", "how to build a GPT for customer support replies", "Current help articles, refund policy, tone rules, and escalation matrix.", "Restrict the GPT to a reply draft with linked policy evidence and a separate escalation flag. Define situations requiring a human specialist.", "Draft a reply using the approved knowledge base. Cite the article behind each instruction, avoid unapproved concessions, and flag safety, legal, or payment issues for review.", "A support agent verifies the account and policy, then approves the reply. Test edge cases before sharing the GPT with a team.", "Correct first responses and escalation misses in a weekly sample."),
            ("Build a GPT for Proposal Scope Checks", "gpt-proposal-scope-checker", "how to build a GPT to check proposal scope", "Approved service catalog, proposal template, signed discovery notes, and pricing authority rules.", "Compare a proposed scope against source commitments and label additions, missing exclusions, and ambiguous acceptance criteria.", "Review this proposal against approved discovery notes and service definitions. List unsupported deliverables and missing exclusions with source references. Do not create prices.", "The account lead resolves differences with delivery and finance before the proposal is sent.", "Scope changes after signature and proposal errors found by delivery."),
            ("Build a GPT for Content Briefs", "gpt-content-brief-generator", "how to build a GPT for SEO content briefs", "Search intent, existing URL inventory, audience questions, product facts, and source links.", "Require a unique target query, reader outcome, outline, evidence needs, and internal links. Force a collision check against the existing page map.", "Create a content brief for this query. Compare it with the existing URL list; if the intent overlaps, recommend updating that URL. Include unique angle, evidence to collect, and useful internal links.", "An editor verifies the search intent and does not publish a second page for the same question.", "Briefs rejected for overlap and published pages with a clearly distinct intent."),
            ("Build a GPT for Onboarding Q&A", "gpt-new-hire-onboarding-qa", "how to build a GPT for new hire onboarding questions", "Approved onboarding guide, current policies, role-specific checklists, and HR contact path.", "Limit answers to the employee's role and cite the current guide. If the question concerns pay, leave, or personal circumstances, route it to HR.", "Answer this new hire question from approved onboarding material. Cite the page and effective date; if the policy is silent or personal, provide the HR escalation path.", "HR checks access permissions and a sample of answers before rollout and whenever policies change.", "Correct self-service answers and repeated onboarding questions routed to HR."),
            ("Build a GPT for Invoice Coding Suggestions", "gpt-invoice-coding-suggestions", "how to build a GPT for invoice coding suggestions", "Chart of accounts, approved vendor list, prior coding examples, and invoice images or text.", "Ask for a proposed category with evidence, a confidence flag, and an exception queue for unfamiliar charges. Keep posting permission separate.", "Suggest an account code for each invoice line using our approved chart and examples. Show the matching rule and flag new vendors or ambiguous charges; do not post entries.", "A bookkeeper verifies the vendor, amount, tax treatment, and account before any entry is recorded.", "Manual recoding rate and exceptions correctly routed for review."),
            ("Build a GPT for Real Estate Guest Messages", "gpt-guest-message-draft-short-term-rental", "how to build a GPT for short term rental guest message drafts", "Property-specific house rules, check-in instructions, support contacts, and current booking details.", "Constrain the GPT to property-specific answers and a draft message, with escalation for safety, access failure, refunds, and disputes.", "Draft a guest reply from this property's approved guide. Use only confirmed booking details, cite the relevant rule internally, and flag any safety or compensation issue for the host.", "The host verifies the right property and reservation and approves any message that affects access or money.", "Repeat guest questions and messages corrected before sending."),
            ("Test a Custom GPT Before Team Rollout", "test-custom-gpt-before-team-rollout", "how to test a custom GPT for a small business team", "Ten normal examples, five edge cases, expected answers, and a named workflow owner.", "Run a fixed test set, score factual accuracy, refusal when evidence is missing, correct escalation, and output format. Retest after instruction or source changes.", "For each test case, compare the GPT response with the expected answer. Record source support, missed exceptions, and whether a human would need to correct it before use.", "The owner approves deployment only when critical errors are resolved and staff know how to report failures.", "Critical error count and percentage of outputs accepted after human review."),
        ],
    },
    {
        "slug": "ai-department-playbooks",
        "title": "AI Playbooks by Business Function",
        "description": "Focused AI workflows for sales, service, finance, operations, and leadership teams in small businesses.",
        "intro": "A business function owns an outcome, not a tool. These guides start with a team handoff or recurring decision and show where an AI draft can help. Use the existing process owner, source of truth, and approval route rather than creating a parallel shadow process.",
        "decision": "Pick the page that matches your team and the artifact it needs. Use the ChatGPT or Claude hubs for tool-specific execution. Where an article already covers general AI adoption, these pages address the narrower job and its measurable handoff.",
        "guides": [
            ("AI for Sales Lead Qualification", "ai-sales-lead-qualification-workflow", "how to use AI for small business lead qualification", "Lead form answers, ideal-customer criteria, service geography, and consent status.", "Draft a qualification score with evidence for each criterion and a question for missing information. Route uncertain or high-value leads to a person.", "Evaluate this lead against our written fit criteria. Show the evidence for each criterion, ask one missing question, and do not infer budget from job title or company size.", "A salesperson reviews scores and decides outreach priority; never let an unverified classification suppress a legitimate inquiry.", "Qualified meeting rate and false rejections found in a weekly sample."),
            ("AI for Sales-to-Delivery Handoffs", "ai-sales-to-delivery-handoff", "how to use AI for sales to delivery handoffs", "Signed agreement, discovery notes, promised milestones, and delivery capacity.", "Produce a handoff brief with deliverables, exclusions, customer stakeholders, risks, and unanswered questions.", "Create a delivery handoff from the signed scope and notes. Separate contractual commitments from sales discussion, cite the source, and flag promises without an owner.", "Sales and delivery leads agree on scope before kickoff and resolve any conflict with the customer.", "Kickoff surprises and change requests traced to missing handoff facts."),
            ("AI for Customer Support Ticket Routing", "ai-support-ticket-routing-small-business", "how to use AI to route small business support tickets", "Ticket text, product or service category, priority policy, and current queue owners.", "Suggest category, urgency, and destination with a short reason. Define a high-risk path for safety, security, and billing disputes.", "Classify this ticket under our routing policy. Return destination and evidence. If urgency or account identity is uncertain, send it to manual triage rather than guessing.", "A lead samples routed tickets and owns the escalation queue, especially outside business hours.", "First-assignment accuracy and time until a high-priority ticket reaches its owner."),
            ("AI for Accounts Receivable Follow-Up", "ai-accounts-receivable-follow-up-drafts", "how to use AI to draft accounts receivable follow-ups", "Verified aging report, payment terms, dispute notes, and customer contact preferences.", "Segment undisputed overdue balances by age and draft a courteous reminder with exact invoice references and a reply path.", "Draft a payment reminder using only these verified invoices and terms. Exclude disputed amounts, state the balance and due date, and invite the customer to report a payment already made.", "Finance verifies balances and disputes and approves every outbound message according to collections policy.", "Collection response time and corrections to reminders sent."),
            ("AI for Weekly KPI Commentary", "ai-weekly-kpi-commentary", "how to use AI to write weekly KPI commentary", "Current and prior KPI exports, metric definitions, target values, and known one-off events.", "Calculate changes outside the model, then ask for a narrative that separates observations from hypotheses and identifies decisions.", "Summarize these verified KPI changes. State the denominator and time period, avoid causal claims without evidence, and list two questions a manager should investigate.", "The analyst checks calculations and context before leadership sees the commentary.", "Time to publish the brief and factual corrections after distribution."),
            ("AI for Inventory Exception Review", "ai-inventory-exception-review", "how to use AI for inventory exception review", "Stock report, reorder rules, lead times, promotions, and recent stockout history.", "Surface items outside thresholds and explain the underlying rule. Ask for a buyer decision rather than silently placing orders.", "From these verified stock figures, list items outside our reorder thresholds with rule, lead time, and missing information. Do not invent demand or create purchase orders.", "The inventory manager checks anomalies against physical counts and supplier constraints.", "Stockouts on reviewed items and false alerts per weekly report."),
            ("AI for Field Service Dispatch Briefs", "ai-field-service-dispatch-brief", "how to use AI for field service dispatch briefs", "Confirmed appointments, job scope, technician skills, location, and access notes.", "Create a technician-facing brief with job objectives, required parts, access constraints, and customer expectations.", "Prepare a dispatch brief from confirmed job records. Highlight missing parts or access details and distinguish customer requests from approved work.", "Dispatch verifies address, schedule, safety notes, and scope before the technician departs.", "Return trips caused by missing information and on-time arrival rate."),
            ("AI for Restaurant Review Response Drafts", "ai-restaurant-review-response-drafts", "how to use AI to draft restaurant review responses", "Public review text, current service policy, and any confirmed incident details.", "Draft a brief public reply acknowledging the actual experience without revealing private records or making claims that cannot be checked.", "Draft a respectful response to this review. Refer only to public details, avoid blaming the guest or staff, and provide a private follow-up route for specifics.", "A manager checks tone and facts and personally handles any food safety or discrimination allegation.", "Response time and the share of replies needing manager rewrite."),
            ("AI for Agency Creative Brief Handoffs", "ai-agency-creative-brief-handoff", "how to use AI for a marketing agency creative brief", "Approved client strategy, campaign objective, audience evidence, brand rules, and asset specs.", "Compile a one-page brief with the intended action, proof points, constraints, deliverables, and approval owner.", "Draft a creative brief from these approved inputs. Cite the source of every product claim, separate required copy from ideas, and mark missing approvals.", "The strategist confirms the objective and the client approves claims before creative production.", "Brief revisions after design starts and assets rejected for missing requirements."),
            ("AI for Property Management Maintenance Intake", "ai-property-maintenance-intake", "how to use AI for property management maintenance intake", "Resident report, property record, emergency criteria, vendor coverage, and consent to enter.", "Structure the issue, ask for missing details, and escalate urgent hazards according to policy. Avoid diagnosing from a text description alone.", "Classify this maintenance report using our emergency policy. List location, symptoms, access permission, and missing facts. Escalate possible hazards for immediate human review.", "A property manager verifies urgency and tenant communications before assigning a vendor.", "Time to triage true emergencies and visits delayed by missing access details."),
            ("AI for Nonprofit Donor Thank-You Drafts", "ai-nonprofit-donor-thank-you-drafts", "how to use AI to draft nonprofit donor thank you messages", "Donation record, approved impact statements, donor preferences, and acknowledgement rules.", "Draft a personal but accurate note that reflects the gift and approved program outcomes without claiming a direct impact that cannot be established.", "Write a donor thank-you from this verified record and approved impact language. Include the right acknowledgement details, avoid invented beneficiary stories, and respect contact preferences.", "Development staff checks amounts, names, restrictions, and any tax language before sending.", "Corrections to acknowledgements and time from gift to accurate thanks."),
            ("AI for Executive Decision Briefs", "ai-executive-decision-brief", "how to use AI to draft an executive decision brief", "Decision deadline, options, verified economics, stakeholder input, and explicit constraints.", "Frame the decision in one page: options, evidence, trade-offs, downside, and what new information would change the choice.", "Write a decision brief from these sources. Show the strongest case for each option, cite figures, identify assumptions, and state which decision leadership must make.", "The executive owner checks evidence and chooses the course; the model cannot substitute for accountable judgment.", "Decision cycle time and decisions revisited because a key assumption was omitted."),
        ],
    },
    {
        "slug": "ai-governance-measurement",
        "title": "AI Governance and ROI for Small Business",
        "description": "Practical controls for choosing AI pilots, protecting data, measuring results, and deciding when to scale.",
        "intro": "An AI pilot needs a baseline, a reviewer, and a stop rule. These guides help small teams make decisions about data, access, quality, and economics without turning every task into a software project. Adapt controls to the actual sensitivity and impact of the workflow.",
        "decision": "Start with the pilot scorecard when choosing a task, the data guide before sharing records, and the evaluation guide before wider rollout. The general AI strategy pillar explains the portfolio; these pages provide operating controls for individual workflows.",
        "guides": [
            ("Choose a First AI Pilot for a Small Business", "choose-first-ai-pilot-small-business", "how to choose a first AI pilot for a small business", "A list of recurring tasks, current time spent, error rates, data sensitivity, and process owners.", "Score each task on frequency, clarity of output, ease of human review, and harm from error. Start with a reversible, draft-only use case.", "Rank these tasks for a four-week AI pilot. Show the evidence for time savings, review burden, sensitivity, and risk. Flag missing baselines and recommend a smallest useful test.", "The owner approves one task, a reviewer, budget, and stop conditions before starting.", "Net minutes saved after review and the error rate against the old process."),
            ("Measure AI Workflow ROI After Human Review", "measure-ai-workflow-roi-human-review", "how to measure AI workflow ROI after human review", "Baseline time per task, volume, tool spend, review time, correction time, and quality outcomes.", "Calculate net time as baseline time minus AI preparation, review, and rework. Compare quality on the same task mix and disclose small sample sizes.", "Create an ROI worksheet from these verified observations. Show gross and net time savings separately, monthly volume, costs, correction rate, and assumptions needing more data.", "Finance validates calculations and a process owner decides whether the measured result is worth continuing.", "Net cost per accepted output and quality compared with the baseline."),
            ("Write a Small Business AI Data Policy", "small-business-ai-data-policy-checklist", "how to write a small business AI data policy", "Existing confidentiality terms, data categories, approved tools, retention rules, and escalation contacts.", "Define permitted, restricted, and prohibited data; approved use cases; sharing and retention rules; and incident reporting in employee-friendly language.", "Draft a one-page AI use policy from these approved requirements. Specify what staff can input, what needs approval, how outputs are reviewed, and who handles suspected exposure. Mark legal gaps.", "Leadership, legal, and security owners approve the policy and confirm vendor settings before distribution.", "Policy exceptions and staff questions that reveal unclear categories."),
            ("Redact Customer Data Before AI Analysis", "redact-customer-data-before-ai-analysis", "how to redact customer data before using AI", "A representative record, the business question, internal data classification, and approved handling rules.", "Keep only fields required for the question, replace direct identifiers with stable tokens, and store the mapping outside the prompt.", "Identify fields essential to answer this question and propose a redacted example. Flag direct and indirect identifiers; do not retain names, account numbers, or free-text secrets.", "The data owner checks whether combinations of remaining fields can reidentify a person and verifies approved tool use.", "Sensitive fields included unnecessarily and analyses that remain useful after minimization."),
            ("Create an AI Output Review Checklist", "ai-output-review-checklist-business", "how to create an AI output review checklist for business", "Representative AI drafts, known failure cases, source-of-truth documents, and intended audience.", "Make checks specific to the artifact: source support, names, numbers, dates, permissions, promises, tone, and escalation triggers.", "Design a review checklist for this workflow. For each failure mode include what to inspect, source to compare, reviewer role, and what blocks release.", "A team lead tests the checklist on errors already found and simplifies it enough to be used consistently.", "Defects escaping review and minutes spent reviewing each output."),
            ("Compare ChatGPT and Claude for a Business Task", "compare-chatgpt-claude-business-task", "how to compare ChatGPT and Claude for a business workflow", "The same approved task input, expected output, scoring rubric, budget, and data controls.", "Run the same cases through each tool under permitted settings. Score accuracy, citation usefulness, editing effort, consistency, and cost per accepted output.", "Evaluate both tools on these identical test cases. Use the same rubric, document differences with examples, and separate model quality from prompt or source differences.", "The workflow owner repeats tests when products change and checks vendor terms before using sensitive data.", "Accepted outputs per hour and total cost including human correction."),
            ("Set Human Approval Gates for AI Automation", "human-approval-gates-ai-automation", "how to set human approval gates for AI automation", "Workflow map, potential impact of errors, existing sign-off rules, and authorized roles.", "Mark steps that create external commitments, move money, change records, or affect people. Require an explicit review at each consequential boundary.", "Map this workflow and label read, draft, approve, and execute steps. Assign an authorized human to each consequential action and show what evidence the reviewer sees.", "Operations tests that a mistaken draft cannot bypass the gate and that approval is logged.", "Unauthorized actions and time spent at each approval stage."),
            ("Audit an AI Prompt Library for Stale Rules", "audit-ai-prompt-library-stale-rules", "how to audit a business AI prompt library", "Prompt inventory, owners, linked policies, last review dates, and recent failures.", "Identify prompts with missing owners, outdated source links, duplicated jobs, and unsafe permissions. Retire or merge overlapping instructions.", "Review this prompt inventory. Group duplicate intent, identify references to obsolete policies, and propose a keep, revise, or retire decision with an owner.", "Each owner validates the revised prompt on a fixed example set before reactivation.", "Prompts with a current owner and recurring errors tied to stale instructions."),
            ("Build an AI Pilot Evaluation Set", "build-ai-pilot-evaluation-set", "how to build an AI evaluation set for a business workflow", "Historical examples, verified expected outputs, edge cases, and common failure reports.", "Sample ordinary and difficult cases, remove sensitive details where needed, and record the expected result and severity of each error.", "Create a test matrix for this workflow: input type, expected result, source evidence, failure severity, and reviewer. Include missing-data and conflicting-data cases.", "Subject-matter reviewers validate expected answers and prevent test examples from being used to tune only for the score.", "Critical errors detected before rollout and coverage of known exceptions."),
            ("Decide Whether to Build or Buy an AI Workflow", "build-versus-buy-ai-workflow-small-business", "how to decide whether to build or buy an AI workflow", "Current task volume, integration needs, vendor options, internal skills, and security requirements.", "Compare configured off-the-shelf tools with a custom build on time to value, maintenance owner, data controls, and exit costs.", "Prepare a build-versus-buy matrix for this workflow. Separate required from optional features, estimate ongoing review and maintenance, and list unknown vendor terms.", "The owner tests a real workflow before contract signature and verifies procurement and security requirements.", "Total cost per accepted result and months until the workflow delivers usable value."),
            ("Train Staff to Report AI Errors", "train-staff-report-ai-errors", "how to train employees to report AI errors", "Examples of wrong outputs, reporting channel, severity definitions, and workflow ownership.", "Teach staff to capture the input type, output, source conflict, potential impact, and whether anything was sent or executed.", "Turn these known failures into a short staff exercise. For each example ask what is wrong, whether work must stop, who to notify, and what evidence to preserve.", "The workflow owner closes the loop with prompt, source, or process changes and tells reporters what changed.", "Time from discovery to containment and repeated failures after a fix."),
            ("Review AI Vendor Data Terms for a Pilot", "review-ai-vendor-data-terms-pilot", "how to review AI vendor data terms for a small business pilot", "Vendor terms, privacy documentation, intended data types, contract, and internal requirements.", "Create a question list on retention, training use, access, subprocessors, deletion, logging, and export. Record where each answer comes from.", "Map our pilot's data to the vendor's published terms. Cite the relevant clause or documentation, mark unanswered questions, and avoid assuming a consumer setting applies to a business plan.", "Legal and security owners verify current terms and approve any sensitive-data use before upload.", "Unanswered material questions before pilot launch and time to remove data at pilot end."),
        ],
    },
]


def all_guides():
    for cluster in CLUSTERS:
        for title, slug, query, source, process, prompt, review, measure in cluster["guides"]:
            yield cluster, {"title": title, "slug": slug, "query": query, "source": source,
                            "process": process, "prompt": prompt, "review": review, "measure": measure}


def validate(existing_urls):
    urls = [f"/ai/{c['slug']}/" for c in CLUSTERS]
    urls += [f"/ai/{c['slug']}/{g['slug']}/" for c, g in all_guides()]
    queries = [g["query"].lower() for _, g in all_guides()]
    if len(urls) != len(set(urls)) or set(urls) & set(existing_urls):
        raise ValueError("AI guide URL collision with existing content")
    if len(queries) != len(set(queries)):
        raise ValueError("Duplicate AI guide search intent")
    if len(CLUSTERS) != 5 or any(len(c["guides"]) != 12 for c in CLUSTERS):
        raise ValueError("Expected five hubs with twelve unique spokes each")
    guide_slugs = {g["slug"] for _, g in all_guides()}
    if guide_slugs != set(TRIALS):
        raise ValueError(f"Trial mismatch: missing={guide_slugs - set(TRIALS)}, extra={set(TRIALS) - guide_slugs}")


def render_hub(cluster, header, breadcrumbs, footer):
    path = f"/ai/{cluster['slug']}/"
    crumbs = [("Home", "/"), ("AI Business Strategy", "/ai-business-strategy/"), (cluster["title"], None)]
    cards = "".join(f'<div class="pill"><h3><a href="{path}{g[1]}/">{escape(g[0])}</a></h3><p>{escape(g[2].capitalize())}. Start with {escape(g[3])}</p></div>' for g in cluster["guides"])
    peers = "".join(f'<li><a href="/ai/{c["slug"]}/">{escape(c["title"])}</a></li>' for c in CLUSTERS if c is not cluster)
    return header(cluster["title"], cluster["description"], path,
                  og_image="/images/dr-connor-robertson-headshot.jpg", page_type="CollectionPage",
                  crumbs=crumbs) + breadcrumbs(crumbs) + f'''<section class="pg-hero"><div class="ctn">
<h1>{escape(cluster['title'])}</h1><p>{escape(cluster['description'])}</p></div></section>
<section class="sec"><div class="ctn"><h2>How to use these guides</h2>
<p>{escape(cluster['intro'])}</p><p>{escape(cluster['decision'])}</p>
<p>Each page covers one outcome with required inputs, a method, a starting prompt, a review gate, and a metric. Test the draft on a small, approved sample before making it part of a team process. Record the human owner and update the workflow when policy or source documents change.</p>
<h2>Choose the deliverable you need</h2><div class="pills">{cards}</div>
<h2>Explore another workflow family</h2><ul class="link-list">{peers}</ul>
<p>For prioritization and deployment across the company, read the <a href="/ai-business-strategy/">AI business strategy guide</a>.</p>
</div></section>''' + footer()


def render_guide(cluster, guide, header, breadcrumbs, footer, site_url, person_id):
    hub = f"/ai/{cluster['slug']}/"
    path = f"{hub}{guide['slug']}/"
    e = escape
    crumbs = [("Home", "/"), ("AI Business Strategy", "/ai-business-strategy/"), (cluster["title"], hub), (guide["title"], None)]
    guides = cluster["guides"]
    index = next(i for i, g in enumerate(guides) if g[1] == guide["slug"])
    # Rotate contextual links instead of sending every page to the same first
    # three siblings. Every guide now receives several crawlable inbound links.
    related_guides = []
    for offset in (-2, -1, 1, 2, 3):
        candidate = guides[(index + offset) % len(guides)]
        if candidate[1] != guide["slug"] and candidate not in related_guides:
            related_guides.append(candidate)
    related = "".join(f'<li><a href="{hub}{g[1]}/">{e(g[0])}</a></li>' for g in related_guides)
    previous = guides[index - 1] if index > 0 else None
    following = guides[index + 1] if index + 1 < len(guides) else None
    previous_url = f"{hub}{previous[1]}/" if previous else ""
    next_url = f"{hub}{following[1]}/" if following else ""
    sequence = '<nav aria-label="Workflow guide sequence" style="display:flex;justify-content:space-between;gap:24px;margin-top:36px;padding-top:24px;border-top:1px solid var(--border)">'
    sequence += (f'<a rel="prev" href="{previous_url}">&larr; {e(previous[0])}</a>' if previous else '<span></span>')
    sequence += (f'<a rel="next" href="{next_url}">{e(following[0])} &rarr;</a>' if following else '<span></span>')
    sequence += '</nav>'
    article = {"@type": "TechArticle", "@id": f"{site_url}{path}#guide", "headline": guide["title"],
               "author": {"@id": person_id}, "publisher": {"@id": person_id},
               "datePublished": "2026-09-22", "dateModified": "2026-09-22",
               "mainEntityOfPage": {"@id": f"{site_url}{path}#webpage"},
               "about": guide["query"], "inLanguage": "en-US"}
    description = f"{guide['query'].capitalize()}: source material, a reusable prompt, a trial case, and a human review check."
    return header(guide["title"], description, path, og_image="/images/dr-connor-robertson-headshot.jpg",
                  crumbs=crumbs, schema_nodes=[article], prev_url=previous_url,
                  next_url=next_url) + breadcrumbs(crumbs) + f'''<section class="pg-hero"><div class="ctn">
<h1>{e(guide['title'])}</h1><p>{e(guide['process'])}</p>
<p class="guide-meta">Published September 22, 2026 · Dr. Connor Robertson</p></div></section>
<section class="sec"><article class="ctn" style="max-width:880px">
<h2>What to provide</h2><p>{e(guide['source'])}</p>
<h2>Starting prompt</h2><blockquote><p>{e(guide['prompt'])}</p></blockquote>
<h2>Trial case</h2><p>{e(TRIALS[guide['slug']])}</p>
<h2>Review gate</h2><p>{e(guide['review'])}</p>
<h2>How to score the result</h2><p>{e(guide['measure'])}</p>
<p>Use the current approved source and keep it available to the reviewer. Check a small set of finished outputs against the previous process before adopting this workflow.</p>
<h2>Related workflows</h2><p>Explore <a href="{hub}">{e(cluster['title'])}</a> or the <a href="/ai-business-strategy/">AI business strategy guide</a>.</p>
<ul class="link-list">{related}</ul>{sequence}</article></section>''' + footer()
